project:
  type: website
  output-dir: docs
 

website:
  title: "Bebop Paleo"
  navbar:
    left:
      - href: index.qmd
        text: Welcome 
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



